### ISSUE TITLE
How would COBYQA behave on feasiblity problems?

### ISSUE THREAD

**Issue by zaikunzhang** [cobyqa/cobyqa#106]
Suppose that the problem has not objective function, or the objective function is a constant. How would COBYQA behave? Will `self.penalty` be always zero? Will the predicted / actual reduction be always zero? What will happen to the reduction ratio and the update of the trust region radius?

CUTEst contains many feasibility problems.

**Comment by ragonneau** [comment]
That's a very good question, I will investigate. I believe the Byrd-Omojokun approach will attempt to minimize the constraint violation anyway, but I need to make sure this is what is observed in practice.

**Comment by zaikunzhang** [comment]
Sorry, I do not think we are thinking about the same thing. My question is independent of the subproblem solver. My question is one level higher. I am thinking about the predicted/actual reduction and the reduction ratio, no matter how the trial step is generated. 

Think about it and talk to me. Do not let things go.
