### ISSUE TITLE
COBYQA does not accept linear constraints?

### ISSUE THREAD

**Issue by zaikunzhang** [cobyqa/cobyqa#109]
Looking at the problem formulated at https://www.cobyqa.com/en/latest/ , I would infer that COBYQA does not accept linear constraints, and I have to wrap linear constraints as nonlinear ones. Is this correct? If yes, then it is a mistake and has to be fixed. If no, then correct the documentation. Thanks.

**Comment by ragonneau** [comment]
I will update the documentation.

Cheers,
Tom.
