### ISSUE TITLE
Put an `if` in powell2015.py to avoid  requiring matplot

### ISSUE THREAD

**Issue by zaikunzhang** [cobyqa/cobyqa#149]
First, print the result in the same way as other examples. In addition, if matplot is available, then plot; otherwise, if you want, print a message saying that the plot is skipped.

**Comment by zaikunzhang** [comment]
Hi Tom, thank you for the quick response. The README may need updating accordingly.

**Comment by ragonneau** [comment]
You are right, I will update that!
