### ISSUE TITLE
ValueError: `x0` is infeasible with respect to some inequality constraint (even though it is within bounds)

### ISSUE THREAD

**Issue by schmoelder** [cobyqa/cobyqa#155]
Hi devs and congrats for the inclusion of `COBYQA` in `scipy`; it's a very much appreciated update to `COBYLA`!

I have an issue with a rather trivial problem. When running the following:

```Python
from scipy import optimize


def objective_function(x):
    return x[0] - x[1]


x0 = [-0.5, 1.5]

bounds = optimize.Bounds(
    lb=[-2., -2.],
    ub=[0., 2.],
    keep_feasible=True
)

scipy_results = optimize.minimize(
    objective_function,
    x0=x0,
    method="COBYQA",
    bounds=bounds,
)

```

I get the following error:

```sh
ValueError: `x0` is infeasible with respect to some inequality constraint with `keep_feasible` set to True.
```

Even though `x0` is well within bounds.

Could you please provide me with some guidance?

Thanks and best wishes

Johannes

**Comment by schmoelder** [comment]
Btw, I assume, this is because of this line here:

https://github.com/cobyqa/cobyqa/blob/0a6bda248da177e15c62e0a51e26040b98f05f57/cobyqa/problem.py#L139

I suppose, you have to pass `x0` instead of `np.ones(bounds.lb.size)`.

**Comment by ragonneau** [comment]
Hi @schmoelder,

First, thank you very much for your words.

It seems you are right. There are other places where `PreparedConstraint` is called. Could you propose a PR patching this problem?

Thanks,
Tom.

**Comment by schmoelder** [comment]
I already played around a bit with the source code. I could get it to run for my problem but it gets a bit more complicated when scaling is involved (which I do outside of COBYQA). I'll have another look tomorrow.

**Comment by zaikunzhang** [comment]
Thank you @schmoelder !

> it's a very much appreciated update to COBYLA

However, COBYQA is not an update to COBYLA. They are completely different algorithms. 

Unless you are a researcher in numerical optimization, it is fairly safe to say that COBYQA and COBYLA have no relation at all except that they aim to solver the same class of problems and share similar names (for good reasons).

**Comment by schmoelder** [comment]
Fair point.

**Comment by zaikunzhang** [comment]
Is this fixed? @ragonneau

**Comment by ragonneau** [comment]
Hi @zaikunzhang,

Sorry for the very long delay. I have not yet worked on that matter. I plan to write a patch on a weekend where I am free, hopefully in the beginning of september.

Cheers,
Tom.

**Comment by ragonneau** [comment]
Hi @schmoelder,

Sorry for the way-too-long delay... I just pushed a patch to this in the COBYQA repo. I will propose later a PR on the SciPy repo.

I close this issue, but feel free to comment if you need to discuss this problem further.

Cheers,
Tom.

**Comment by schmoelder** [comment]
Hey Tom,

thank you so much and no worries, I had offered to look into it but it eventually stalled. Looking forward to the updates in scipy! :nerd_face: 

Cheers,

Jo
