### ISSUE TITLE
Add default values for options in documentation

### ISSUE THREAD

**Issue by schmoelder** [cobyqa/cobyqa#156]
It would be handy to provide the default values for the options in the `minimize` function. E.g. what's the default number of `maxfev`?

For comparison, check other optimizers in scipy, e.g. [`trust-constr`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-trustconstr.html).

**Edit:** I realize this might be more of an issue for the SciPy repo. Are you maintaining this as well or should I open another issue over there?

**Comment by nickodell** [comment]
Agreed that this would be super useful. Often I'm in a position where I want to raise or lower, say, ftol, and the first question I have is "what's the current value for ftol if I don't provide it?" That gives me a place to start by multiplying or dividing that value by 10. For most of SciPy's minimization methods, I have to manually spelunk through the code to figure that out.

The obvious place to put this information in the SciPy is [this page](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-cobyqa.html), though I don't understand why the defaults in the function here...

```
def _minimize_cobyqa(fun, x0, args=(), bounds=None, constraints=(),
                     callback=None, disp=False, maxfev=None, maxiter=None,
                     f_target=-np.inf, feasibility_tol=1e-8,
                     initial_tr_radius=1.0, final_tr_radius=1e-6, scale=False,
                     **unknown_options):
```

don't get picked up in the docs [here](https://docs.scipy.org/doc/scipy/reference/optimize.minimize-cobyqa.html).

**Comment by ragonneau** [comment]
Hi @schmoelder @nickodell,

Thank you for the issue. This is indeed an easy improvement that should be made.

This repo is a submodule of SciPy and is maintained. I added the default value in the doc of COBYQA (see 0cb666abbb5364b6e12b749351b2799ebd3119c5 and https://www.cobyqa.com/latest/ref/generated/cobyqa.minimize.html). I should also update the doc on the SciPy repo, I will prepare a PR.

Cheers,
Tom.

**Comment by ragonneau** [comment]
I close this issue as the related PR was merged on SciPy's repo.

Cheers,
Tom.
