### ISSUE TITLE
Use current best point in callbacks

### ISSUE THREAD

**Issue by schmoelder** [cobyqa/cobyqa#157]
In the callbacks, `COBYQA` currently uses the latest point `x`. However, this is inconsistent with the other optimizers in `scipy` which use the current best point (see also: https://github.com/scipy/scipy/issues/21061).

**Comment by ragonneau** [comment]
Hi @schmoelder,

If I recall correctly, most methods in SciPy call the callback function at the end of each iteration. This does not make sense in derivative-free optimization. At the moment, the callback in COBYQA is called after every function evaluations. Which mechanism do you expect exactly?

Cheers,
Tom.
