### ISSUE TITLE
Make the expriments reproducible

### ISSUE THREAD

**Issue by zaikunzhang** [cobyqa/cobyqa#90]
### Feature description

For profiling, the testing problem set must be fixed (while being sufficiently large). It is hard to draw any conclusion based on the comparison on a changing set of problems.

**Please, please**, fix the "loading failure" problem of PyCutest **before starting to make ANY comparison**. It feels **very frustrating** for me to see that the comparison results are not reproducible/consistent due to loading failures of testing problems. If this is impossible due to defects of PyCutest, then turn to a different solution.

I do not want to encounter ever again loading failure problems in our later investigation, no matter on GitHub Actions or on local computers.

I do not want to encounter ever again the situation that "this comparison result is different from my last experiment, and I do not know/remember what happened". This has happened too many times in our previous investigations, and it is very annoying.

We have been working on this project for a sufficiently long time to avoid any non-reproducible experiments. 

Thanks.

**Comment by ragonneau** [comment]
The new version of the benchmarking script does not suffer from the problem we met before.

Cheers,
Tom.
